apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: togglemaster
type: Opaque
data:
  POSTGRES_HOST: dG9nZ2xlbWFzdGVyLWF1dGgtcG9zdGdyZXMuYzY3NGh4aHRqNzZtLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  POSTGRES_DB: dG9nZ2xlbWFzdGVyX2F1dGg=
  POSTGRES_USER: dG1fdXNlcg==
  POSTGRES_PASSWORD: dG9nZ2xlbWFzdGVyMTIz
