apiVersion: v1
kind: Secret
metadata:
  name: flag-db-secret
  namespace: togglemaster
type: Opaque
data:
  POSTGRES_HOST: dG9nZ2xlbWFzdGVyLWZsYWctcG9zdGdyZXMuYzY3NGh4aHRqNzZtLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  POSTGRES_DB: dG9nZ2xlbWFzdGVyX2ZsYWc=
  POSTGRES_USER: dG1fdXNlcg==
  POSTGRES_PASSWORD: dG9nZ2xlbWFzdGVyMTIz