apiVersion: v1
kind: Secret
metadata:
  name: targeting-db-secret
  namespace: togglemaster
type: Opaque
data:
  POSTGRES_HOST: dG9nZ2xlbWFzdGVyLXRhcmdldGluZy1wb3N0Z3Jlcy5jNjc0aHhodGo3Nm0udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  POSTGRES_DB: dG9nZ2xlbWFzdGVyX3RhcmdldGluZw==
  POSTGRES_USER: dG1fdXNlcg==
  POSTGRES_PASSWORD: dG9nZ2xlbWFzdGVyMTIz
