name: Auth Service CI

on:
  push:
    branches: ["main"]
    paths:
      - "Kubernetes/auth-service/**"
      - ".github/workflows/auth-service.yml"

  pull_request:
    branches: ["main"]
    paths:
      - "Kubernetes/auth-service/**"
      - ".github/workflows/auth-service.yml"

jobs:

# -------------- BUILD & TEST --------------------

  build_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Kubernetes/auth-service/auth-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - run: go mod tidy
      - run: go build ./...

      - name: Run tests
        run: go test ./... || echo "No tests found"

      - name: Build Docker image
        run: docker build -t auth-service:ci -f Dockerfile .


# ---------------- LINT ----------------
  lint:
    runs-on: ubuntu-latest
    needs: build_test

    defaults:
      run:
        working-directory: Kubernetes/auth-service/auth-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Download modules
        run: go mod tidy && go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: Kubernetes/auth-service/auth-service
          args: --timeout=5m ./...

# ---------------- SECURITY ----------------

  security:
    runs-on: ubuntu-latest
    needs: lint

    defaults:
      run:
        working-directory: Kubernetes/auth-service/auth-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Download modules
        run: go mod tidy && go mod download

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec -severity high ./...

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: Kubernetes/auth-service/auth-service
          severity: CRITICAL
          exit-code: "1"
