name: Auth Service CI

on:
  push:
    branches: ["main"]
    paths:
      - "Kubernetes/auth-service/**"
      - ".github/workflows/auth-service.yml"

  pull_request:
    branches: ["main"]
    paths:
      - "Kubernetes/auth-service/**"
      - ".github/workflows/auth-service.yml"

jobs:

# -------------- BUILD & TEST --------------------

  build_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Kubernetes/auth-service/auth-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - run: go mod tidy
      - run: go build ./...

      - name: Run tests
        run: go test ./... || echo "No tests found"

      - name: Build Docker image
        run: docker build -t auth-service:ci -f Dockerfile .


# ---------------- LINT ----------------
  lint:
    runs-on: ubuntu-latest
    needs: build_test

    defaults:
      run:
        working-directory: Kubernetes/auth-service/auth-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Download modules
        run: go mod tidy && go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: Kubernetes/auth-service/auth-service
          args: --timeout=5m ./...

# ---------------- SECURITY ----------------

  security:
    runs-on: ubuntu-latest
    needs: lint

    defaults:
      run:
        working-directory: Kubernetes/auth-service/auth-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Download modules
        run: go mod tidy && go mod download

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec -severity high ./...

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: Kubernetes/auth-service/auth-service
          severity: CRITICAL
          exit-code: "1"


# ---------------- DOCKER PUSH ----------------

  docker_build_push:
    runs-on: ubuntu-latest
    needs: security

    if: github.event_name == 'push' && github.ref == 'refs/heads/Main'

    defaults:
      run:
        working-directory: Kubernetes/auth-service/auth-service

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          COMMIT_SHA=${GITHUB_SHA::7}
          docker build -t auth-service:${COMMIT_SHA} .
          docker tag auth-service:${COMMIT_SHA} auth-service:latest

      - name: Trivy Container Scan
        run: |
          COMMIT_SHA=${GITHUB_SHA::7}
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image --severity CRITICAL --exit-code 1 \
            auth-service:${COMMIT_SHA}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Push to ECR
        run: |
          COMMIT_SHA=${GITHUB_SHA::7}
          ECR=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          REPO=${{ secrets.PROJECT_NAME }}/auth-service

          docker tag auth-service:${COMMIT_SHA} $ECR/$REPO:${COMMIT_SHA}
          docker tag auth-service:${COMMIT_SHA} $ECR/$REPO:latest

          docker push $ECR/$REPO:${COMMIT_SHA}
          docker push $ECR/$REPO:latest
